org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
org.gradle.daemon=true
org.gradle.parallel=false

# Minecraft
minecraft_version=1.20.1

# Fabric
fabric_loader_version=0.19.2
fabric_api_version=0.92.9+1.20.1

# Forge
forge_version=47.4.10
mapping_channel=official
mapping_version=1.20.1

# NeoForge
neo_version=20.6.125

# Mod
mod_id=crosshairtargetfilter
mod_name=CrosshairTarget Filter
mod_version=1.0.0
mod_logo=logo.png
mod_description=Interact through anything.
mod_url=https://github.com/LitnhJacuzzi/CrosshairTarget-Filter
issues_url=https://github.com/LitnhJacuzzi/CrosshairTarget-Filter/issues
license=GPL 3.0
author=LitnhJacuzzi

# Dependencies
modmenu_version=7.2.2
clothconfig_version=11.1.136